FROM python:3.11-slim

WORKDIR /usr/src/app

COPY payment-service/requirements.txt /usr/src/app/

RUN pip install -r requirements.txt

COPY payment-service /usr/src/app
COPY custom_consul /usr/src/app/custom_consul

ENV PYTHONPATH=/usr/src/app

EXPOSE 5050

CMD ["python", "main.py"]