#Dockerfile.auth_db
FROM python:3.11-slim

WORKDIR /usr/src/app

COPY auth-service/requirements.txt /usr/src/app/

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt  

COPY auth-service/register_auth_db.py /usr/src/app/


CMD ["python", "register_auth_db.py"]
