FROM python:3.11-slim

WORKDIR /usr/src/app

COPY api-gateway/requirements.txt /usr/src/app/

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt  

COPY api-gateway /usr/src/app
COPY auth-service/templates /usr/src/app/templates
COPY event-service/templates /usr/src/app/templates
COPY booking-service/templates /usr/src/app/templates
COPY custom_consul /usr/src/app/custom_consul

EXPOSE 8080

CMD ["python3", "main.py"]
