###    API gateway
GET http://localhost:8080/health
Accept: text/html

###    API gateway
GET http://localhost:8080/events
Accept: text/html


###    Event-service
GET http://localhost:8082/health
Accept: text/html

### 
GET http://localhost:8082/events
Accept: text/html




###facade-service:8080 /events
POST http://localhost:8080/facade_service
Content-Type: application/json

{
  "msg": "msg10"
}

###